<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Blog</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <link rel="stylesheet" href="../public/style.css" />
</head>
<body>
  <main>
    <section>
      <img src="http://designyoutrust.com/wp-content/uploads/2013/07/g411.jpg"/>
      <button class="details"><a href="../src/newUser.php" class="connex">Inscription</a></button>
      <button class="details"><a href="../src/login.php" class="connex">connexion</a></button>
      <button class="details"><a href="../src/logout.php" class="connex">Se deconnecter</a></button>
      <button class="details"><a href="../src/listeArticle.php" class="connex">Afficher la listes des articles</a></button>

<h1><i class="fas fa-paint-brush"></i><font color="#ffffff">B</font><font color="#fdf4f4">i</font><font color="#fbe9e9">e</font><font color="#f8dede">n</font><font color="#f6d3d3">v</font><font color="#f4c8c8">e</font><font color="#f2bcbc">n</font><font color="#efb1b1">u</font><font color="#eda6a6">e</font><font color="#eb9b9b"> </font><font color="#e99090">s</font><font color="#e78585">u</font><font color="#e47a7a">r</font><font color="#e26f6f"> </font><font color="#e06464">m</font><font color="#de5959">o</font><font color="#dc4e4e">n</font><font color="#d94343"> </font><font color="#d73737">b</font><font color="#d52c2c">l</font><font color="#d32121">o</font><font color="#d01616">g</font><font color="#ce0b0b"> </font><font color="#cc0000">!</font><i class="fas fa-paint-brush"></i></h1>

      <?php include $template ?>

    </section>
  </main>
</body>
</html>
