<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Blog</title>
  <link rel="stylesheet" href="../public/style.css">
</head>
<body>
  <main>
    <section>
      <img src="http://www.lacontreallee.com/sites/default/files/imagecache/Apercu/blog_67_32.jpg" />
      <h1>Blog</h1>

      <?php include $template ?>


      <form action="index.php" method="post">

        <fieldset>
          <legend>création de billet</legend>

          <label for="titre">titre (10 characters max):</label>
          <input type="text" id="titre" name="titre" required maxlength="10">

          <label for="texte">Description</label>
          <textarea id="texte" name="texte"></textarea>

          <button type="submit">creer</button>

        </fieldset>
      </form>
    </section>
  </main>
</body>
</html>
