<?php if (isset($_SESSION['user'])) { ?>
  <p><?= $_SESSION['user']['pseudo'] ?></p>
<?php } ?>
<form action="newBillet.php" method="post" enctype="multipart/form-data">
  <fieldset>
    <legend>création de billet</legend>

    <label for="titre">titre (10 characters max):</label>
    <input type="text" id="titre" name="titre" value="" required maxlength="10">

    <label for="texte">Description</label>
    <textarea id="texte" name="texte" value=""></textarea>

    <label for="image">Inserez une image</label>
    <input type="file" name="image" class="details">

    <button type="submit" value="" class="details">creer</button>
    <label for="categorie">Choisissez une catégorie:</label>
    <select id="categorie">
      <option value="">-- Choisissez une categorie --</option>
      <option value="categorieUn">categorie1</option>
      <option value="categorieDeux">categorie2</option>
      <option value="categorieTrois">categorie3</option>
    </select>


  </fieldset>
</form>
