<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Blog</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <link rel="stylesheet" href="../public/style.css" />
</head>
<body>
  <main>
    <section>
      <nav>
        <button class="details"><a href="../templates/home.phtml" class="connex">Acceuil</a></button>
        <button class="details"><a href="../src/newUser.php" class="connex">Inscription</a></button>
        <button class="details"><a href="../src/login.php" class="connex">connexion</a></button>
        <button class="details"><a href="../src/logout.php" class="connex">Se deconnecter</a></button>
        <button class="details"><a href="../src/newBillet.php" class="connex">Creer un article</a></button>
        <button class="details"><a href="../src/listeArticle.php" class="connex">Afficher la listes des articles</a></button>
      </nav>

      <h1><i class="fas fa-paint-brush"></i><font color="#000000">b</font><font color="#00000c">i</font><font color="#000018">e</font><font color="#000024">n</font><font color="#000031">v</font><font color="#00003d">e</font><font color="#000049">n</font><font color="#000055">u</font><font color="#000061">e</font><font color="#00006d"> </font><font color="#000079">s</font><font color="#000086">u</font><font color="#000092">r</font><font color="#00009e"> </font><font color="#0000aa">m</font><font color="#0000b6">o</font><font color="#0000c2">n</font><font color="#0000ce"> </font><font color="#0000db">b</font><font color="#0000e7">l</font><font color="#0000f3">o</font><font color="#0000ff">g</font><i class="fas fa-paint-brush"></i></h1>
      <p class="intro">Un blog haut en couleur ! Naviguez a votre guise =). La peinture de rue est présente en Europe depuis le 16e siècle. À l’époque, ces peintres (aussi appelés « artistes de la craie ») créaient et décoraient de grandes murailles sur des murs intérieurs de luxueuses villas. </p>

      <img src="http://designyoutrust.com/wp-content/uploads/2013/07/g411.jpg" class="imgheader"/>
      <p class="intro">Évidemment, plus vous jouerez bien, plus le public appréciera. Votre originalité et votre performance artistique seront vos meilleurs atouts. Pour autant, tout comme moi, vous n’éviterez sûrement pas les fausses notes : souriez, et poursuivez ! Dialoguez avec votre public, suscitez la curiosité, et provoquez les interactions. Une petite blague glissée au bon moment, un clin d’œil à un enfant qui vous regarde, un merci quand on vous glisse une pièce : ne jouez pas pour vous, mais bien pour les passants.</p>
    </section>
  </main>
</body>
</html>
