<form action="newUser.php" method="post">
  <fieldset>
    <legend>Inscription</legend>

    <label for="name">Name</label>
    <input type="text" id="username" name="name" placeholder="Jean">

    <label for="firstname">firstname</label>
    <input type="text" id="username" name="firstname" placeholder="Francois">

    <label for="pseudo">pseudo</label>
    <input type="text" id="username" name="pseudo" placeholder="superman">

    <label for="password">Password</label>
    <input id="password" name="password" placeholder="********">

    <label for="mail"/>votre email :</label>
    <input type="email" name="mail" placeholder="exemple@gmail.fr"/>

    <button type="submit" value="" class="details">Je m'inscris !</button>
    <button class="details"><a href="../src/newBillet.php"><i class="fas fa-undo-alt"></i>Annuler</a></button>
  </fieldset>
</form>
